version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=galaxeye
    ports:
      - 27017:27017  
    volumes:
      - ./data:/data/db
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   environment:
  #     - BACKEND_API=http://backend:8000
  #   ports:
  #     - 8000:3000
  #   restart: always

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   environment:
  #     - DATABASE_URI=mongodb://mongodb:27017/galaxeye  
  #   container_name: backend
  #   restart: always